### PR TITLE
Fixed Testing

### PR DESCRIPTION
**Pull request by CodeLenny**
Hi guys.  I'm working on adding [file upload](https://docs.gitlab.com/ce/api/projects.html#upload-a-file) to projects, but found out that the tests are failing.  I got the tests [working](https://travis-ci.org/CodeLenny/gitlab/builds/170860283), so figured I'd submit a PR.

Do these changes look all right?  I made project names randomly generated with [objectid](https://www.npmjs.com/package/objectid), as there's a [bug](https://gitlab.com/gitlab-org/gitlab-ce/issues/13384) in GitLab CE when you create a project with the same name as a previously deleted project.

### CODE REVIEW

**Comment by fengmk2** [comment]
Nice job! 👍

**Comment by fengmk2** [comment]
Thanks a lot @CodeLenny

**Comment by fengmk2** [comment]
@CodeLenny invite you to join the collaborators group.

**Comment by CodeLenny** [comment]
@fengmk2 Glad to help!

**Pull request merged**
