### PR TITLE
Adds support for MR notes

### PR DESCRIPTION
**Pull request by selvagsz**
https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/notes.md#merge-requests

- [x] Implementation
- [ ] Tests
- [x] Docs

### CODE REVIEW

**Comment by selvagsz** [comment]
@fengmk2 do you have any docs or pointers for the test coverage ?

**Comment by fengmk2** [comment]
@selvagsz you can follow the `issues` test case https://github.com/repo-utils/gitlab/blob/master/test/issue.test.js

**Comment by selvagsz** [comment]
okay. I found some time to debug the tests. It seems the `default_branch` is set to `null` while creating a project. MR test cases requires a source and a target branch(`master`)

screen shot 2016-03-17 at 8 58 53 pm

**Comment by selvagsz** [comment]
@fengmk2 since the `default_branch` is null, couldn't able to create a branch coz it needs a source branch. Any pointers ? I'd be happy to see this gets merged

**Comment by fengmk2** [comment]
@selvagsz can you rebase master and run test again?

**Comment by dfalling** [comment]
@selvagsz any luck getting the tests working for this?  I've tried this PR locally and the merge request endpoints are exactly what I was looking for.

**Comment by selvagsz** [comment]
@dfalling Haven't found time to look back at this. Will check tonight

**Comment by selvagsz** [comment]
@fengmk2 Facing the same issue still. The `default_branch` is `null` while creating a project. I'd suggest to create a new project `fengmk2/node-gitlab-test-1` with master branch and use that repo for the test cases.

screen shot 2016-06-03 at 4 27 04 pm

**Comment by selvagsz** [comment]
@fengmk2 Its better to create a new user account in gitlab for the test cases. I don't think its good to expose your `privateToken` for test cases

**Comment by selvagsz** [comment]
@fengmk2 any update on this ?

**Comment by fengmk2** [comment]
LGTM

**Comment by fengmk2** [comment]
1.3.0 release

**Pull request merged**
