### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by dfalling**
This merge request fixes the tests that are currently failing due to changes in gitlab's API (primarily unexpected keys in responses.)

### CODE REVIEW

**Comment by dfalling** [comment]
The travis build failed, but I'm not having that issue locally (via `npm run test` or `npm run test-travis`.)  Has anyone encountered this failure before?

**Comment by digabit** [comment]
Passing tests!  Sadly I didn't do much.  It seems gitlab's test API is a bit unreliable and occasionally returns 400's.  Are there any additional changes I need to make to this to get it merged in?  Thanks!

**Comment by dfalling** [comment]
Passing tests! Sadly I didn't do much. It seems gitlab's test API is a bit unreliable and occasionally returns 400's. Are there any additional changes I need to make to this to get it merged in? Thanks!

**Comment by dfalling** [comment]
Is this project still maintained?

**Comment by fengmk2** [comment]
@dfalling Sorry for reply too late.

👍

**Comment by dfalling** [comment]
No worries, thanks for this great project!

**Pull request merged**
